#check global variables
IF(NOT VERSION_FILE)
	message("Error: The VERSION_FILE variable not defined!")
	return(1)
ENDIF()

IF(NOT RESOURCE_FILE)
	message("Error: The RESOURCE_FILE variable not defined!")
	return(1)
ENDIF()


IF(NOT PACKAGE_NAME)
	message("Error: The PACKAGE_NAME variable not defined!")
	return(1)
ENDIF()

#check files exists
IF(NOT EXISTS ${VERSION_FILE})
	message("Error: No ${VERSION_FILE} available")
	return(1)
ENDIF()

IF(NOT EXISTS ${RESOURCE_FILE})
	message("Error: No ${RESOURCE_FILE} available")
	return(1)
ENDIF()


#read version from file
file(READ ${VERSION_FILE} VERSION)

string(REGEX MATCH "VERSION_MAJOR ([0-9]*)" _ ${VERSION})
set(MAJOR ${CMAKE_MATCH_1})

string(REGEX MATCH "VERSION_MINOR ([0-9]*)" _ ${VERSION})
set(MINOR ${CMAKE_MATCH_1})

string(REGEX MATCH "VERSION_PATCH ([0-9]*)" _ ${VERSION})
set(PATCH ${CMAKE_MATCH_1})

string(REGEX MATCH "VERSION_SUFFIX ([0-9]*)" _ ${VERSION})
set(SUFFIX ${CMAKE_MATCH_1})

math(EXPR SUFFIX "${SUFFIX}+1")

#Update file
file(WRITE ${VERSION_FILE} 
	"VERSION_MAJOR ${MAJOR}\n"
	"VERSION_MINOR ${MINOR}\n"
	"VERSION_PATCH ${PATCH}\n"
	"VERSION_SUFFIX ${SUFFIX}"
)

#Create resource file
file(WRITE ${RESOURCE_FILE}
	"//This file is automatically generated by build_number.cmake\n"
	"#include \"resource.h\"\n"
	"#define APSTUDIO_READONLY_SYMBOLS\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"//\n"
	"// Generated from the TEXTINCLUDE 2 resource.\n"
	"//\n"
	"#include \"winres.h\"\n"
	"\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"#undef APSTUDIO_READONLY_SYMBOLS\n"
	"\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"// Russian (Russia) resources\n"
	"\n"
	"#if !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_RUS)\n"
	"LANGUAGE LANG_RUSSIAN, SUBLANG_DEFAULT\n"
	"#pragma code_page(1251)\n"
	"\n"
	"#ifdef APSTUDIO_INVOKED\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"//\n"
	"// TEXTINCLUDE\n"
	"//\n"
	"\n"
	"1 TEXTINCLUDE\n" 
	"BEGIN\n"
    "\"resource.h\\0\"\n"
	"END\n"
	"\n"
	"2 TEXTINCLUDE\n" 
	"BEGIN\n"
	"\"#include \"\"winres.h\"\"\\r\\n\"\n"
    "\"\\0\"\n"
	"END\n"
	"\n"
	"3 TEXTINCLUDE\n" 
	"BEGIN\n"
    "\"\\r\\n\"\n"
    "\"\\0\"\n"
	"END\n"
	"\n"
	"#endif    // APSTUDIO_INVOKED\n"
	"\n"
	"#endif    // Russian (Russia) resources\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"\n"
	"\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"// English (United States) resources\n"
	"\n"
	"#if !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_ENU)\n"
	"LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US\n"
	"#pragma code_page(1252)\n"
	"\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"//\n"
	"// Version\n"
	"//\n"
	"\n"
	"VS_VERSION_INFO VERSIONINFO\n"
	"FILEVERSION ${MAJOR},${MINOR},${PATCH},${SUFFIX}\n"
	"PRODUCTVERSION ${MAJOR},${MINOR},${PATCH},${SUFFIX}\n"
	"FILEFLAGSMASK 0x3fL\n"
	"#ifdef _DEBUG\n"
	"	FILEFLAGS 0x1L\n"
	"#else\n"
	"	FILEFLAGS 0x0L\n"
	"#endif\n"
	"FILEOS 0x40004L\n"
	"FILETYPE 0x1L\n"
	"FILESUBTYPE 0x0L\n"
	"BEGIN\n"
    "	BLOCK \"StringFileInfo\"\n"
    "		BEGIN\n"
    "			BLOCK \"040904b0\"\n"
    "		BEGIN\n"
    "			VALUE \"FileVersion\", \"${MAJOR}.${MINOR}.${PATCH}.${SUFFIX}\"\n"
    "			VALUE \"InternalName\", \"app.exe\"\n"
    "			VALUE \"LegalCopyright\", \"Copyright (C) 2020\"\n"
    "			VALUE \"OriginalFilename\", \"${PACKAGE_NAME}\"\n"
    "			VALUE \"ProductName\", \"${PACKAGE_NAME}\"\n"
    "			VALUE \"ProductVersion\", \"${MAJOR}.${MINOR}.${PATCH}.${SUFFIX}\"\n"
    "		END\n"
    "END\n"
    "BLOCK \"VarFileInfo\"\n"
    "BEGIN\n"
    "	VALUE \"Translation\", 0x409, 1200\n"
    "END\n"
	"END\n"
	"\n"
	"IDR_VERSION2 VERSIONINFO\n"
	"FILEVERSION ${MAJOR},${MINOR},${PATCH},${SUFFIX}\n"
	"PRODUCTVERSION ${MAJOR},${MINOR},${PATCH},${SUFFIX}\n"
	"FILEFLAGSMASK 0x3fL\n"
	"#ifdef _DEBUG\n"
	"	FILEFLAGS 0x1L\n"
	"#else\n"
	"	FILEFLAGS 0x0L\n"
	"#endif\n"
	"FILEOS 0x40004L\n"
	"FILETYPE 0x0L\n"
	"FILESUBTYPE 0x0L\n"
	"BEGIN\n"
    "BLOCK \"StringFileInfo\"\n"
    "BEGIN\n"
    "	BLOCK \"040904b0\"\n"
    "	BEGIN\n"
    "		VALUE \"FileDescription\", \"\"\n"
    "		VALUE \"FileVersion\", \"${MAJOR}.${MINOR}.${PATCH}.${SUFFIX}\"\n"
    "		VALUE \"InternalName\", \"${PACKAGE_NAME}\"\n"
    "		VALUE \"LegalCopyright\", \"Copyright (C) 2020\"\n"
    "		VALUE \"OriginalFilename\", \"${PACKAGE_NAME}\"\n"
    "		VALUE \"ProductName\", \"${PACKAGE_NAME}\"\n"
    "		VALUE \"ProductVersion\", \"${MAJOR}.${MINOR}.${PATCH}.${SUFFIX}\"\n"
    "	END\n"
    "END\n"
    "BLOCK \"VarFileInfo\"\n"
    "BEGIN\n"
	"	VALUE \"Translation\", 0x409, 1200\n"
    "END\n"
	"END\n"
	"\n"
	"#endif    // English (United States) resources\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"\n"
	"\n"
	"\n"
	"#ifndef APSTUDIO_INVOKED\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"//\n"
	"// Generated from the TEXTINCLUDE 3 resource.\n"
	"//\n"
	"\n"
	"\n"
	"/////////////////////////////////////////////////////////////////////////////\n"
	"#endif    // not APSTUDIO_INVOKED\n"
)
